-- Drop and recreate Goals table

DROP TABLE IF EXISTS goals CASCADE;


CREATE TABLE goals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  -- end_date DATE NOT NULL,
  created TIME DEFAULT CURRENT_TIME,
  status INTEGER DEFAULT 0,
  category VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

