-- Drop and recreate Tasks table

DROP TABLE IF EXISTS tasks CASCADE;


CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  details VARCHAR(255) NOT NULL,
  created DATE DEFAULT CURRENT_TIMESTAMP,
  complete_by DATE DEFAULT '2022-07-20T05:00:00.000Z',
  is_completed BOOLEAN DEFAULT FALSE,
  goal_id INTEGER REFERENCES goals(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

